### ISSUE TITLE
Install doesn't work on WIndows 10

### ISSUE THREAD

**Issue by dkeza** [jbutko/ExpressJS-Socket.IO-AngularJS-Boilerplate#1]
Hi, I am trying to use your boilerplate on 
```
Microsoft Windows [Version 10.0.16299.192] 64 Bit
npm 5.6.0
node 8.9.4
```
Install in client folder works. But in server folder after npm install I receive this error:
```
'bower' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! expressjs-angularjs-boilerplate@1.0.0 postinstall: `npm i gulp-sass --save-dev&&npm i gulp-imagemin --save-dev&&bower install --no-interactive --allow-root`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the expressjs-angularjs-boilerplate@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jbutko** [comment]
@dkeza Hi, there is no npm script/prescript/postscript in `server/package.json` which is using `bower` command. Only client app uses bower to install dependencies. One possible cause might be that you do not have `bower` installed globaly. To fix it you can issue `npm i -g bower` command.

**Comment by dkeza** [comment]
OK, thank You, ```npm i -g bower``` solved it, it works now!
